management:
  endpoints:
    web:
      base-path: /manage

server:
  servlet:
    contextPath: /management-monitoring

spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssXXX
    time-zone: America/Winnipeg
    serialization:
      write-dates-as-timestamps: false
  jpa:
    open-in-view: false
  mvc:
    static-path-pattern: /resources/**
