management:
  endpoint:
    health:
      show-details: when-authorized
  endpoints:
    web:
      base-path: /manage
      exposure:
        include:
        - health
        - info
        - prometheus
        - metrics

server:
  servlet:
    contextPath: /management-monitoring

spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssXXX
    time-zone: America/Winnipeg
    serialization:
      write-dates-as-timestamps: false
  jpa:
    open-in-view: false
  mvc:
    static-path-pattern: /resources/**
